<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { CalendarDays, ChevronRight, CircleEllipsis, Heart, Home, Lightbulb, MapPin, MessageSquare, Moon, Plus, Search, Send, Settings, ShieldCheck, Sparkles, Users, X } from '@lucide/vue'

type Person = { id:string; name:string; age:number; city:string; distance:string; job:string; match:number; image:string; tags:string[]; bio:string; reasons:string[] }
const router = useRouter(); const route = useRoute()
const screen = computed(() => route.meta.screen as string || 'landing')
const onboarding = ref<'intro'|'chat'|'ready'|'dashboard'>('intro')
const message = ref(''); const selectedPlace = ref('cafe'); const safety = ref(true); const liked = ref(false)
const people = ref<Person[]>([
  {id:'daniel',name:'Daniel',age:31,city:'Berlin',distance:'3 km',job:'Product Designer',match:88,image:'https://i.pravatar.cc/800?img=12',tags:['Nature','Good food','Meaningful relationships','Long-term oriented'],bio:'Thoughtful, curious, and happiest near a good meal or a long walk.',reasons:['You both value deep conversations and personal growth.','You share a long-term outlook and respect independence.','You both enjoy nature, good food, and meaningful experiences.','Your communication styles complement each other.']},
  {id:'emma',name:'Emma',age:28,city:'Berlin',distance:'5 km',job:'Curator',match:93,image:'https://i.pravatar.cc/800?img=47',tags:['Deep conversations','Travel','Art','Mental health'],bio:'Art lover with a calm, warm way of making every day feel considered.',reasons:['You make room for curiosity.']},
  {id:'sophie',name:'Sophie',age:26,city:'Berlin',distance:'7 km',job:'Photographer',match:87,image:'https://i.pravatar.cc/800?img=44',tags:['Art','Personal growth','Spontaneous plans','Nature'],bio:'A quietly adventurous photographer looking for shared stories.',reasons:['You both look for meaning in small moments.']},
  {id:'james',name:'James',age:30,city:'Berlin',distance:'4 km',job:'Engineer',match:86,image:'https://i.pravatar.cc/800?img=11',tags:['Tech','Hiking','Meaningful relationships','Adventure'],bio:'A builder, hiker and attentive listener with a playful side.',reasons:['You share a practical curiosity.']},
])
const daniel = computed(() => people.value[0])
const nav = [{to:'/home',label:'Home',icon:Home},{to:'/people',label:'People',icon:Users},{to:'/chat',label:'Chat',icon:MessageSquare},{to:'/plans',label:'Plan',icon:ShieldCheck},{to:'/settings',label:'Settings',icon:Settings}]
const places = [
  {id:'cafe',title:'Café & Walk in Kreuzberg',text:'A relaxed first date with good food and an easy canal-side walk.',fit:92,time:'1.5–2 hours',kind:'Casual',image:'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=900&q=80'},
  {id:'walk',title:'Sunset Walk by the Canal',text:'Nature, fresh air, and space for a real conversation.',fit:89,time:'1–1.5 hours',kind:'Outdoor',image:'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=900&q=80'},
  {id:'gallery',title:'Contemporary Art & Coffee',text:'A shared curiosity with a relaxed place to talk afterward.',fit:86,time:'About 2 hours',kind:'Culture',image:'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=900&q=80'},
]
const messages = ref([{from:'them',text:'Hey! I saw you enjoy nature and good food. Is there a place in Berlin you always go back to?',time:'10:14 AM'},{from:'me',text:'There’s a little Italian place near Kreuzberg I love. I usually pair it with a walk along the canal.',time:'10:16 AM'},{from:'them',text:'That sounds great. I’m always up for a walk by the water. Want to try it together this weekend?',time:'10:18 AM'},{from:'me',text:'I’d like that! Let’s plan something relaxed.',time:'10:19 AM'}])
function go(to:string){ router.push(to) }
function send(){ if(message.value.trim()){ messages.value.push({from:'me',text:message.value,time:'Now'}); message.value='' } }
onMounted(async()=>{ try { const result=await fetch('/api/people'); if(result.ok) people.value=await result.json() } catch { /* offline demo data remains */ } })
</script>

<template>
  <main v-if="screen === 'landing'" class="landing page-nebula">
    <div class="landing-card"><div class="brand"><span class="logo">✦</span>Soulprint</div><CircleEllipsis class="more"/><div class="landing-copy"><h1>More than a match.<br><em>A deeper you.</em></h1><p>AI-powered connections for dating, friendship,<br>and everything in between.</p><button class="cta" @click="go('/home')">Get Started <ChevronRight/></button><small>Real conversations.<br>Meaningful connections.<br>A safer experience.</small></div></div>
  </main>
  <main v-else class="app-shell page-nebula">
    <aside class="rail"><div class="brand"><span class="logo">✦</span>Soulprint</div><nav><button v-for="item in nav" :key="item.to" :class="{active: route.path === item.to || (item.to === '/home' && screen === 'home')}" @click="go(item.to)"><component :is="item.icon"/>{{ item.label }}</button></nav></aside>
    <section class="workspace"><header><div class="search"><Search/> <span>Search people, interests, or topics...</span></div><div class="header-actions"><button class="invite"><Plus/> Invite a Friend</button><CircleEllipsis/><img class="avatar" src="https://i.pravatar.cc/100?img=32" alt="Your profile"></div></header>
      <section v-if="screen === 'home' && onboarding === 'intro'" class="onboarding panel"><div class="progress"><i></i><span>1 / 15</span></div><div class="question"><span class="orb">✦</span><div>Let’s get to know you better ✨</div></div><div class="question"><span class="orb">✦</span><div><b>What are you here for?</b><small>You can always change this later.</small></div></div><div class="choice-grid"><button @click="onboarding='chat'"><Heart/> <b>Dating</b><small>Romantic relationships</small></button><button @click="onboarding='chat'"><Users/> <b>Friendship</b><small>Meaningful friendships</small></button><button @click="onboarding='chat'"><Sparkles/> <b>Both</b><small>Open to both</small></button></div><div class="composer muted"><Plus/><span>Choose an option to continue</span><Send/></div></section>
      <section v-else-if="screen === 'home' && onboarding === 'chat'" class="onboarding panel"><div class="progress four"><i></i><span>4 / 15</span></div><div class="talk"><div class="question"><span class="orb">✦</span><div>What kind of people make you feel comfortable?</div></div><div class="reply">Open-minded, kind people who enjoy deep conversations, but also simple, fun moments together.</div><div class="question"><span class="orb">✦</span><div>How do you usually spend your free time?</div></div><div class="reply">Long walks, reading, trying new cafés, and unplanned weekends outdoors.</div><div class="question"><span class="orb">✦</span><div>What are you looking for right now?</div></div></div><div class="composer"><Plus/><input placeholder="Type your answer..." @keyup.enter="onboarding='ready'"><button @click="onboarding='ready'"><Send/></button></div></section>
      <section v-else-if="screen === 'home' && onboarding === 'ready'" class="ready"><h1>Your Soulprint is ready.</h1><div class="panel soul-card"><div class="soul-blob"><span>Values</span><span>Interests</span><span>Communication</span><span>Relationships</span><span>Lifestyle</span><span>Social Energy</span><b>✦</b></div><div class="soul-copy"><h2>My Soulprint</h2><p>Independent · Curious · Direct Communicator · Long-term Oriented · High Openness</p><small>You value deep conversations, meaningful experiences, and personal growth. You’re drawn to kind, ambitious people who appreciate both adventure and stability.</small><button class="secondary" @click="onboarding='dashboard'">✎ Edit Soulprint</button></div><div class="insight"><Lightbulb/><b>Connection style</b><small>Your connections thrive on honesty, curiosity, and room to grow.</small></div></div></section>
      <section v-else-if="screen === 'home'" class="dashboard"><h1>Your Connections, Redefined.</h1><p class="subtitle">Meaningful people. Deeper conversations. A safer journey.</p><div class="dash-grid"><article class="panel soul-summary"><h3>Your Soulprint</h3><div class="mini-blob">✦</div><ul><li>Values</li><li>Communication</li><li>Interests</li><li>Relationships</li><li>Lifestyle</li><li>Social Energy</li></ul></article><article class="panel suggestions"><h3>Today’s Suggestions</h3><div class="suggestion-row"><button v-for="person in people.slice(0,3)" :key="person.id" @click="go('/people/'+person.id)"><img :src="person.image" :alt="person.name"><b>{{person.name}}, {{person.age}}</b><small>{{person.match}}% match</small></button></div></article><article class="panel checkin"><CalendarDays/><div><b>Upcoming Check-in</b><small>Today at 8:00 PM</small></div><button class="secondary">View</button></article><article class="panel activity"><b>Recent Activity</b><span>👥 3 new people liked your Soulprint</span><span>💬 2 new messages</span></article></div></section>
      <section v-else-if="screen === 'people'" class="people"><h1>People who get you.</h1><p class="subtitle">Based on semantic compatibility between Soulprints.</p><div class="tabs"><button class="selected">Dating</button><button>Friendship</button><button>Both</button></div><div class="people-grid"><article v-for="person in people" :key="person.id" class="person-card"><img :src="person.image" :alt="person.name"><button class="heart"><Heart/></button><div><h2>{{person.name}}, {{person.age}}</h2><strong>{{person.match}}% match</strong><p><span v-for="tag in person.tags" :key="tag">{{tag}}</span></p><button class="cta compact" @click="go('/people/'+person.id)">View profile <ChevronRight/></button></div></article></div></section>
      <section v-else-if="screen === 'profile'" class="profile"><img class="profile-photo" :src="daniel.image" alt="Daniel"><div><div class="profile-title"><h1>Daniel, 31</h1><button class="heart" @click="liked=!liked"><Heart :fill="liked?'currentColor':'none'"/></button><CircleEllipsis/></div><strong>88% Soulprint Match 〰</strong><p><MapPin/> Berlin, 3 km</p><p>▣ Product Designer</p><div class="tags"><span>Dating</span><span>Long-term oriented</span></div><hr><h2>Why you might connect</h2><ul class="reasons"><li v-for="reason in daniel.reasons" :key="reason">✦ {{reason}}</li></ul><small>A thoughtful match to explore at your own pace.</small></div><button class="cta like" @click="go('/chat')">Send a Like</button></section>
      <section v-else-if="screen === 'chat'" class="chat-layout"><article class="panel chat"><div class="chat-head"><img :src="daniel.image" alt="Daniel"><div><h2>Daniel, 31</h2><small>● Online</small></div><button class="heart"><Heart/></button><CircleEllipsis/></div><div class="messages"><div v-for="item in messages" :class="['bubble',item.from]" :key="item.text"><img v-if="item.from==='them'" :src="daniel.image" alt=""><p>{{item.text}}<small>{{item.time}}</small></p></div></div><div class="composer"><Plus/><input v-model="message" placeholder="Message Daniel..." @keyup.enter="send"><button @click="send"><Send/></button></div></article><aside class="chat-tools"><button @click="go('/assistant')"><Lightbulb/><b>AI Assistant</b><small>Conversation ideas & gentle help</small><ChevronRight/></button><button @click="go('/date-plan')"><CalendarDays/><b>Plan Date</b><small>Make a plan together</small><ChevronRight/></button><button @click="safety=!safety"><ShieldCheck/><b>Safety</b><small>Your safety tools</small><ChevronRight/></button></aside></section>
      <section v-else-if="screen === 'assistant'" class="assistant panel"><button class="back" @click="go('/chat')">← Return to the chat with Daniel</button><div class="assistant-title"><Lightbulb/><div><h1>AI Assistant</h1><p>Based on your conversation with Daniel</p></div></div><p>Shared interests from your chat</p><div class="idea-grid"><article v-for="idea in ['Italian food|You both enjoy good food. Compare favorite Italian dishes or cafés around Kreuzberg; it could be a relaxed place to meet.','Nature & walks|You both like being outdoors. Ask about Daniel’s favorite canal-side route or green space in Berlin.','Meaningful conversations|You both value deeper conversations. Explore what makes a weekend feel memorable for each of you.']" :key="idea"><Lightbulb/><h2>{{idea.split('|')[0]}}</h2><p>{{idea.split('|')[1]}}</p></article></div></section>
      <section v-else-if="screen === 'date'" class="date panel"><button class="back" @click="go('/chat')">← Return to the chat with Daniel</button><h1>Plan a date with Daniel</h1><p class="subtitle">Ideas based on what you both enjoy.</p><div class="tabs"><button class="selected">AI</button><button>Outdoor</button><button>Culture</button><button>Food</button><button>At home</button></div><div class="place-grid"><button v-for="place in places" :key="place.id" :class="{selected: selectedPlace===place.id}" @click="selectedPlace=place.id"><img :src="place.image" :alt="place.title"><h2>{{place.title}}</h2><p>{{place.text}}</p><small>♡ {{place.fit}}% fit　◷ {{place.time}}</small></button></div><div class="plan-bar"><div><h2>Plan together</h2><small>Pick a time that works for you both. You can always adjust later.</small></div><select><option>This Saturday</option></select><select><option>4:00 PM</option></select><button class="cta" @click="go('/plans')"><Send/> Share plan with Daniel</button></div></section>
      <section v-else-if="screen === 'plans'" class="plans"><button class="invite" @click="go('/date-plan')"><Plus/> Add a new plan</button><h1>Your Plans</h1><p class="subtitle">Make time for the connections that matter.</p><h2>Today</h2><article class="plan-card panel"><img :src="places[0].image" alt="Café"><div><b>Daniel, 31</b><small>● Online</small><h2>Café & Walk in Kreuzberg</h2><p>▣ Today · 4:00 PM　 ◈ Safety on</p><small>Coffee and Italian food, followed by a relaxed canal-side walk.</small></div><div><strong>✓ Confirmed</strong><button class="cta compact">View plan <ChevronRight/></button></div></article><h2>Upcoming</h2><article class="plan-card panel small"><img :src="places[1].image" alt="Museum"><div><b>Sofia, 28</b><h2>Museum & Coffee</h2><p>▣ Sat, May 17 · 3:00 PM</p></div><strong>◷ Planned</strong></article></section>
      <section v-else class="settings"><h1>Settings</h1><p class="subtitle">Make Soulprint feel right for you.</p><div class="settings-grid"><article class="panel"><h2>Profile & Soulprint</h2><button>◉ <span><b>Edit profile</b><small>Update your photos, bio, and basic info</small></span><ChevronRight/></button><button>✦ <span><b>Update my Soulprint</b><small>Answer new questions or refine your answers</small></span><ChevronRight/></button></article><article class="panel"><h2>Privacy & Safety</h2><button>▣ <span><b>Privacy controls</b><small>Manage your visibility and data</small></span><ChevronRight/></button><button>◈ <span><b>Date Safety settings</b><small>Tools for safer, more confident dates</small></span><ChevronRight/></button><button>◉ <span><b>Location sharing</b><small>Share your location during dates</small></span><i class="toggle"></i></button></article><article class="panel"><h2>Discovery preferences</h2><button><span><b>Connection goals</b><small>What are you here for?</small></span><em>Dating　 Friendship　 <mark>Both</mark></em></button><button><span><b>Age range</b><small>25 – 40</small></span><input type="range" value="50"></button><button><span><b>Distance</b><small>25 km</small></span><input type="range" value="38"></button></article><article class="panel"><h2>Notifications</h2><button><span><b>Messages</b><small>New messages and chat activity</small></span><i class="toggle on"></i></button><button><span><b>Date check-ins</b><small>Reminders and safety check-ins</small></span><i class="toggle on"></i></button><button><span><b>Recommendations</b><small>New people and experiences for you</small></span><i class="toggle"></i></button></article></div></section>
    </section>
  </main>
</template>
